# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='datatime',
            field=models.DateField(default='2017-12-07', verbose_name='保存时间'),
        ),
    ]
